I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 52, in script call
    call STORY
  File "game/STORY.rpy", line 247, in script
    $ fading_pause(channel="sound", fade=1.0)
  File "game/STORY.rpy", line 247, in <module>
    $ fading_pause(channel="sound", fade=1.0)
TypeError: fading_pause() got an unexpected keyword argument 'fade'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 52, in script call
    call STORY
  File "game/STORY.rpy", line 247, in script
    $ fading_pause(channel="sound", fade=1.0)
  File "renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/STORY.rpy", line 247, in <module>
    $ fading_pause(channel="sound", fade=1.0)
TypeError: fading_pause() got an unexpected keyword argument 'fade'

Windows-10-10.0.19041 AMD64
Ren'Py 7.6.1.23060707
DDLC - No More Time 0.0.1
Sat Jul  1 15:20:41 2023
